import { google } from "googleapis";

import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { TemperatureChart } from "../components/TemperatureChart";
import { HumidityChart } from "../components/HumidityChart";
import { SheetDataProps } from "../types";

export async function getServerSideProps() {
  const auth = await google.auth.getClient({
    scopes: ["https://www.googleapis.com/auth/spreadsheets.readonly"],
  });

  const sheets = google.sheets({ version: "v4", auth });
  const range = `Sheet1!A:D`;

  const response = await sheets.spreadsheets.values.get({
    spreadsheetId: process.env.SHEET_ID,
    range,
  });

  const sheetData = response?.data?.values;

  return {
    props: {
      sheetData,
    },
  };
}

const Home: NextPage<SheetDataProps> = ({ sheetData }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Temperature Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TemperatureChart sheetData={sheetData} />
        <HumidityChart sheetData={sheetData} />
      </main>
    </div>
  );
};

export default Home;
