import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

import { TemperatureChart } from "../components/TemperatureChart";
import { HumidityChart } from "../components/HumidityChart";
import { SheetDataProps } from "../types";
import { getForecast } from "../services/openMeteo";
import { getGoogleSheetData } from '../services/googleSheets'

export async function getServerSideProps() {
  const sheetData = await getGoogleSheetData()
  const forecast = await getForecast()

  return {
    props: {
      sheetData,
    },
  };
}

const Home: NextPage<SheetDataProps> = ({ sheetData }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Temperature Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TemperatureChart sheetData={sheetData} />
        <HumidityChart sheetData={sheetData} />
      </main>
    </div>
  );
};

export default Home;
